### ISSUE TITLE
配置 alias 失效

### ISSUE THREAD

**Issue by shiyutim** [cyytemplate/vite-electron-ts#2]
使用了这个模板，然后在 vite.config.ts 里面配置 alias 失效，两种方法都试了（也重启了服务）。我在一个普通的vue3 + vite 的项目里，是能够正常使用的。所以，能帮忙看下吗

```
  resolve: {
    // alias: {
    //   '@': resolve(__dirname, 'src'),
    //   'root': root, 
    // }
    alias: [{
      find: '@',
      replacement: resolve(__dirname, 'src')
    },
```

**Comment by cyyjs** [comment]
如果您使用的是项目模板的目录结构，配置应该如下：
`'@': resolve(__dirname, 'src/render')`
注意后面增加`render`目录
该项目我已更新，增加了`@`别名示例，可以下载下来运行查看效果。
