### ISSUE TITLE
npm run dev失败

### ISSUE THREAD

**Issue by Minori-ty** [cyytemplate/vite-electron-ts#4]
![image](https://user-images.githubusercontent.com/79521943/132156244-7db5b6fe-968d-4868-980c-851467b5ccb2.png)
是环境变量的问题，是否考虑装个cross-env？

**Comment by cyyjs** [comment]
`3000`端口被占用了，可以换个端口启动前端项目

**Comment by Minori-ty** [comment]
> `3000`端口被占用了，可以换个端口启动前端项目

所有端口都关了，依旧是环境变量的问题
![image](https://user-images.githubusercontent.com/79521943/132163245-4a54924c-0cf7-4d4e-a288-410c766780a0.png)

**Comment by cyyjs** [comment]
由于`3000`端口被占用，所以vue前端项目默认启动使用了`3001`端口，
你可以修改主进程加载的地址为`3001`端口

**Comment by Minori-ty** [comment]
> 由于`3000`端口被占用，所以vue前端项目默认启动使用了`3001`端口，
> 你可以修改主进程加载的地址为`3001`端口

我在vite.config.js里面修改端口号，也修改了main/index.ts的端口号，都是这样，可能是你程序设置的问题。

**Comment by AyaReiOwO** [comment]
跟我一样的问题，你的解决了嘛

**Comment by Minori-ty** [comment]
> 跟我一样的问题，你的解决了嘛

忘了，不过我用的是另外两个高赞的模板
